version: '3'
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
    networks:
      - my-net

  redis:
    image: "redis:latest"
    networks:
      - my-net

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
      network: host
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    networks:
      - my-net

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
      network: host
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - my-net

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
      network: host
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - my-net
    environment:
      - WDS_SOCKET_PORT=0

  nginx:
    restart: always
    depends_on:
      - api
      - client
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
