name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t aa122aa/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true aa122aa/react-test npm test
      - name: Set up QEMU        
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx        
        uses: docker/setup-buildx-action@v1
      
      - name: Build Docker image
      - run: docker buildx build -t aa122aa/multi-client-10-14 --platform=linux/arm64 ./client
      - run: docker buildx build -t aa122aa/multi-nginx-10-14 --platform=linux/arm64 ./nginx
      - run: docker buildx build -t aa122aa/multi-server-10-14 --platform=linux/arm64 ./server
      - run: docker buildx build -t aa122aa/multi-worker-10-14 --platform=linux/arm64 ./worker
 
      - name: Push Docker image
      - run: docker push aa122aa/multi-client-10-14
      - run: docker push aa122aa/multi-nginx-10-14
      - run: docker push aa122aa/multi-server-10-14
      - run: docker push aa122aa/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
